#!/usr/bin/env bash
# script to fix the nginx listening port and reloads the nginx master process
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
service nginx restart
