#!/usr/bin/env bash
# script to fix the nginx listening port and reloads the nginx master process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
